export const CustomPagesData= [
  {
    id: 1,
    name: "Welcome Bonus Terms",
    slug: "welcome-bonus-terms",
    content: "Terms and conditions for the welcome bonus offer at Grand Fortune Casino.",
    status: "enabled",
    author: "John Doe",
  },
  {
    id: 2,
    name: "VIP Program Details",
    slug: "vip-program-details",
    content: "Information about the VIP program for high rollers, including benefits and tiers.",
    status: "enabled",
    author: "Jane Smith",
  },
  {
    id: 3,
    name: "Free Spins FAQ",
    slug: "free-spins-faq",
    content: "Frequently asked questions about free spins promotions and how to claim them.",
    status: "enabled",
    author: "Alice Johnson",
  },
  {
    id: 4,
    name: "No Deposit Bonus Guide",
    slug: "no-deposit-bonus-guide",
    content: "A guide to understanding and using no deposit bonuses at our casino.",
    status: "enabled",
    author: "Bob Wilson",
  },
  {
    id: 5,
    name: "Loyalty Program Overview",
    slug: "loyalty-program-overview",
    content: "Details on earning and redeeming loyalty points for exclusive rewards.",
    status: "enabled",
    author: "Emma Brown",
  },
  {
    id: 6,
    name: "Cashback Offer Terms",
    slug: "cashback-offer-terms",
    content: "Terms for weekly cashback offers, including eligibility and payout details.",
    status: "disabled",
    author: "Michael Lee",
  },
  {
    id: 7,
    name: "High Roller Bonus Rules",
    slug: "high-roller-bonus-rules",
    content: "Rules and requirements for high roller bonus eligibility and benefits.",
    status: "enabled",
    author: "Sarah Davis",
  },
  {
    id: 8,
    name: "Responsible Gambling Policy",
    slug: "responsible-gambling-policy",
    content: "Our commitment to promoting responsible gambling practices.",
    status: "enabled",
    author: "David Clark",
  },
  {
    id: 9,
    name: "Tournament Schedule",
    slug: "tournament-schedule",
    content: "Schedule and rules for upcoming casino tournaments and events.",
    status: "disabled",
    author: "Laura Martinez",
  },
  {
    id: 10,
    name: "Payment Methods Guide",
    slug: "payment-methods-guide",
    content: "A guide to available payment methods, including deposits and withdrawals.",
    status: "enabled",
    author: "Chris Thompson",
  },
];

