export const SingleCustomPagesData = [
  {
    id: 1,
    name: "Welcome Bonus Terms",
    slug: "welcome-bonus-terms",
    seoTitle: "Welcome Bonus Terms - Grand Fortune Casino",
    metaDescription: "Learn about the terms and conditions for the welcome bonus at Grand Fortune Casino.",
    excerpt: "Understand the rules for claiming and using our welcome bonus offer.",
    body: "<p>Welcome to our casino! The welcome bonus offers a 100% match up to $500. Use [shortcode_promo] to claim. Wagering requirements: 35x.</p>",
    status: "enabled",
    author: "John Doe",
  },
  {
    id: 2,
    name: "VIP Program Details",
    slug: "vip-program-details",
    seoTitle: "VIP Program - Exclusive Benefits",
    metaDescription: "Explore the VIP program at our casino, including tiers and exclusive rewards.",
    excerpt: "Join our VIP program for premium benefits and personalized offers.",
    body: "<p>Our VIP program includes [shortcode_vip_tiers] for Bronze, Silver, Gold, and Platinum levels.</p>",
    status: "enabled",
    author: "Jane Smith",
  },
  {
    id: 3,
    name: "Free Spins FAQ",
    slug: "free-spins-faq",
    seoTitle: "Free Spins FAQ - Casino Guide",
    metaDescription: "Answers to common questions about free spins promotions at our casino.",
    excerpt: "Find out how to claim and use free spins in our casino games.",
    body: "<p><strong>Q: How do I claim free spins?</strong> Use [shortcode_claim_spins].</p>",
    status: "enabled",
    author: "Alice Johnson",
  },
  {
    id: 4,
    name: "No Deposit Bonus Guide",
    slug: "no-deposit-bonus-guide",
    seoTitle: "", // Defaults to name
    metaDescription: "A guide to understanding no deposit bonuses and how to use them effectively.",
    excerpt: "Learn how to play with no deposit bonuses without risking your own money.",
    body: "<p>No deposit bonuses are available with [shortcode_bonus_code].</p>",
    status: "enabled",
    author: "Bob Wilson",
  },
  {
    id: 5,
    name: "Loyalty Program Overview",
    slug: "loyalty-program-overview",
    seoTitle: "Loyalty Program - Earn Rewards",
    metaDescription: "Discover how to earn and redeem loyalty points for exclusive rewards.",
    excerpt: "Earn points with every bet and redeem them for bonuses.",
    body: "<p>Join our loyalty program with [shortcode_loyalty_signup].</p>",
    status: "enabled",
    author: "Emma Brown",
  },
  {
    id: 6,
    name: "Cashback Offer Terms",
    slug: "cashback-offer-terms",
    seoTitle: "Cashback Offer Terms - Weekly Deals",
    metaDescription: "Terms for our weekly cashback offers, including eligibility details.",
    excerpt: "Get cashback every week on your losses with our offer.",
    body: "<p>Cashback is credited every Monday. Use [shortcode_cashback].</p>",
    status: "disabled",
    author: "John Doe",
  },
  {
    id: 7,
    name: "High Roller Bonus Rules",
    slug: "high-roller-bonus-rules",
    seoTitle: "High Roller Bonus Rules",
    metaDescription: "Rules for high roller bonuses, designed for big spenders.",
    excerpt: "Special bonuses for high rollers with exclusive rewards.",
    body: "<p>High rollers can claim with [shortcode_high_roller].</p>",
    status: "enabled",
    author: "Jane Smith",
  },
  {
    id: 8,
    name: "Responsible Gambling Policy",
    slug: "responsible-gambling-policy",
    seoTitle: "Responsible Gambling - Our Commitment",
    metaDescription: "Our policy to promote safe and responsible gambling practices.",
    excerpt: "Learn about our commitment to responsible gambling.",
    body: "<p>We support responsible gambling with [shortcode_support].</p>",
    status: "enabled",
    author: "Alice Johnson",
  },
  {
    id: 9,
    name: "Tournament Schedule",
    slug: "tournament-schedule",
    seoTitle: "Casino Tournament Schedule 2025",
    metaDescription: "Upcoming casino tournaments and event schedules.",
    excerpt: "Check out our latest tournament schedule and join the action.",
    body: "<p>View the full schedule with [shortcode_tournament].</p>",
    status: "disabled",
    author: "Bob Wilson",
  },
  {
    id: 10,
    name: "Payment Methods Guide",
    slug: "payment-methods-guide",
    seoTitle: "Payment Methods - Deposits & Withdrawals",
    metaDescription: "Guide to available payment methods for deposits and withdrawals.",
    excerpt: "Explore secure payment options for your casino account.",
    body: "<p>Supported methods include [shortcode_payment_options].</p>",
    status: "enabled",
    author: "Emma Brown",
  },
];

