export const CasinoGamesData = [
  {
    id: 1,
    name: 'Mega Moolah',
    slug: 'mega-moolah',
    featuredImage: '/images/games/featured/game1.jpg',
    gameType: 'Slot',
    status: 'enabled',
  },
  {
    id: 2,
    name: 'Blackjack Classic',
    slug: 'blackjack-classic',
    featuredImage: '/images/games/featured/game2.jpg',
    gameType: 'Table Game',
    status: 'enabled',
  },
  {
    id: 3,
    name: 'Roulette Royale',
    slug: 'roulette-royale',
    featuredImage: '/images/games/featured/game3.jpg',
    gameType: 'Table Game',
    status: 'disabled',
  },
  {
    id: 4,
    name: 'Live Poker',
    slug: 'live-poker',
    featuredImage: '/images/games/featured/game4.jpg',
    gameType: 'Live Dealer',
    status: 'enabled',
  },
  {
    id: 5,
    name: 'Starburst',
    slug: 'starburst',
    featuredImage: '/images/games/featured/game5.jpg',
    gameType: 'Slot',
    status: 'enabled',
  },
  {
    id: 6,
    name: 'Baccarat Live',
    slug: 'baccarat-live',
    featuredImage: '/images/games/featured/game6.jpg',
    gameType: 'Live Dealer',
    status: 'enabled',
  },
  {
    id: 7,
    name: 'Gonzo’s Quest',
    slug: 'gonzos-quest',
    featuredImage: '/images/games/featured/game7.jpg',
    gameType: 'Slot',
    status: 'enabled',
  },
  {
    id: 8,
    name: 'Lightning Roulette',
    slug: 'lightning-roulette',
    featuredImage: '/images/games/featured/game8.jpg',
    gameType: 'Live Dealer',
    status: 'enabled',
  },
  {
    id: 9,
    name: 'Book of Dead',
    slug: 'book-of-dead',
    featuredImage: '/images/games/featured/game9.jpg',
    gameType: 'Slot',
    status: 'enabled',
  },
  {
    id: 10,
    name: 'Dream Catcher',
    slug: 'dream-catcher',
    featuredImage: '/images/games/featured/game10.jpg',
    gameType: 'Live Dealer',
    status: 'enabled',
  },
];