export const SingleGamesData = [
  {
    id: 1,
    name: 'Mega Moolah',
    slug: 'mega-moolah',
    softwareProvider: 'Microgaming',
    gameType: 'Slot',
    paylines: 25,
    reels: 5,
    minCoinsPerLine: 1,
    maxCoinsPerLine: 5,
    minCoinsSize: 0.01,
    maxCoinsSize: 0.25,
    rtp: 88.12,
    bonusGame: true,
    progressive: true,
    wildSymbol: true,
    scatterSymbol: true,
    autoplayOption: true,
    multiplier: true,
    freeSpins: true,
    seoTitle: 'Mega Moolah Slot Review 2025',
    metaDescription: 'Discover Mega Moolah, a thrilling progressive slot with massive jackpots and exciting features.',
    featuredLogo: '/images/games/featured/game1.jpg',
    screenshotsGallery: [
      '/images/blog/blog-img1.jpg',
      '/images/blog/blog-img2.jpg',
    ],
    excerpt: 'Mega Moolah is a legendary progressive slot known for its life-changing jackpots and engaging gameplay.',
    body: 'Mega Moolah, developed by Microgaming, is one of the most iconic progressive jackpot slots in the online gaming world. With its African safari theme, vibrant graphics, and the potential for massive payouts, it’s a favorite among slot enthusiasts. The game features 25 paylines, 5 reels, and a variety of bonus features, including free spins and multipliers.',
    tags: ['Popular', 'High Roller'],
    featured: true,
    faq: [
      { question: 'What is the RTP of Mega Moolah?', answer: 'The RTP is 88.12%, lower due to its progressive jackpot.' },
      { question: 'Can I play Mega Moolah on mobile?', answer: 'Yes, it’s fully optimized for mobile devices.' },
    ],
    status: 'enabled',
  },
  {
    id: 2,
    name: 'Blackjack Classic',
    slug: 'blackjack-classic',
    softwareProvider: 'NetEnt',
    gameType: 'Table Game',
    paylines: 0,
    reels: 0,
    minCoinsPerLine: 0,
    maxCoinsPerLine: 0,
    minCoinsSize: 1,
    maxCoinsSize: 100,
    rtp: 99.59,
    bonusGame: false,
    progressive: false,
    wildSymbol: false,
    scatterSymbol: false,
    autoplayOption: false,
    multiplier: false,
    freeSpins: false,
    seoTitle: 'Blackjack Classic Review 2025',
    metaDescription: 'Experience the timeless thrill of Blackjack Classic, a high-RTP table game by NetEnt.',
    featuredLogo: '/images/games/featured/game2.jpg',
    screenshotsGallery: [
      '/images/games/screenshots/blackjack-classic-1.jpg',
    ],
    excerpt: 'Blackjack Classic offers a traditional blackjack experience with smooth gameplay and high RTP.',
    body: 'Blackjack Classic by NetEnt delivers a straightforward and engaging blackjack experience. With a high RTP of 99.59%, it’s perfect for players looking to test their strategy against the dealer. The game features crisp visuals and intuitive controls, making it accessible for both new and experienced players.',
    tags: ['Popular'],
    featured: false,
    faq: [
      { question: 'What is the RTP of Blackjack Classic?', answer: 'The RTP is 99.59%.' },
      { question: 'Does Blackjack Classic have side bets?', answerastas: 'No, it focuses on core blackjack gameplay.' },
    ],
    status: 'enabled',
  },
  {
    id: 3,
    name: 'Roulette Royale',
    slug: 'roulette-royale',
    softwareProvider: 'Microgaming',
    gameType: 'Table Game',
    paylines: 0,
    reels: 0,
    minCoinsPerLine: 0,
    maxCoinsPerLine: 0,
    minCoinsSize: 1,
    maxCoinsSize: 200,
    rtp: 97.3,
    bonusGame: false,
    progressive: true,
    wildSymbol: false,
    scatterSymbol: false,
    autoplayOption: false,
    multiplier: false,
    freeSpins: false,
    seoTitle: 'Roulette Royale Game Review',
    metaDescription: 'Spin the wheel with Roulette Royale, a thrilling table game with a progressive jackpot.',
    featuredLogo: '/images/games/featured/game3.jpg',
    screenshotsGallery: [
      '/images/games/screenshots/roulette-royale-1.jpg',
    ],
    excerpt: 'Roulette Royale combines classic roulette with a progressive jackpot for added excitement.',
    body: 'Roulette Royale, developed by Microgaming, offers a classic roulette experience with the added thrill of a progressive jackpot. With a 97.3% RTP, it’s a great choice for players who enjoy strategic betting and high-stakes rewards.',
    tags: ['Exclusive'],
    featured: false,
    faq: [
      { question: 'What makes Roulette Royale unique?', answer: 'It features a progressive jackpot that grows with each spin.' },
    ],
    status: 'disabled',
  },
  {
    id: 4,
    name: 'Live Poker',
    slug: 'live-poker',
    softwareProvider: 'Evolution Gaming',
    gameType: 'Live Dealer',
    paylines: 0,
    reels: 0,
    minCoinsPerLine: 0,
    maxCoinsPerLine: 0,
    minCoinsSize: 5,
    maxCoinsSize: 500,
    rtp: 98.5,
    bonusGame: false,
    progressive: false,
    wildSymbol: false,
    scatterSymbol: false,
    autoplayOption: false,
    multiplier: false,
    freeSpins: false,
    seoTitle: 'Live Poker Review 2025',
    metaDescription: 'Join the action with Live Poker, a real-time table game by Evolution Gaming.',
    featuredLogo: '/images/games/featured/game4.jpg',
    screenshotsGallery: [
      '/images/games/screenshots/live-poker-1.jpg',
      '/images/games/screenshots/live-poker-2.jpg',
    ],
    excerpt: 'Live Poker offers an immersive real-time poker experience with professional dealers.',
    body: 'Live Poker by Evolution Gaming brings the excitement of a real poker table to your screen. With professional dealers and high-quality streaming, it offers an authentic casino experience with a 98.5% RTP.',
    tags: ['Popular', 'Exclusive'],
    featured: true,
    faq: [
      { question: 'Is Live Poker available on mobile?', answer: 'Yes, it’s optimized for mobile play.' },
      { question: 'What is the RTP of Live Poker?', answer: 'The RTP is approximately 98.5%.' },
    ],
    status: 'enabled',
  },
  {
    id: 5,
    name: 'Starburst',
    slug: 'starburst',
    softwareProvider: 'NetEnt',
    gameType: 'Slot',
    paylines: 10,
    reels: 5,
 shiny: true,
    minCoinsPerLine: 1,
    maxCoinsPerLine: 10,
    minCoinsSize: 0.01,
    maxCoinsSize: 1,
    rtp: 96.09,
    bonusGame: false,
    progressive: false,
    wildSymbol: true,
    scatterSymbol: false,
    autoplayOption: true,
    multiplier: false,
    freeSpins: true,
    seoTitle: 'Starburst Slot Review 2025',
    metaDescription: 'Play Starburst, a vibrant slot with expanding wilds and exciting gameplay.',
    featuredLogo: '/images/games/featured/game5.jpg',
    screenshotsGallery: [
      '/images/games/screenshots/starburst-1.jpg',
      '/images/games/screenshots/starburst-2.jpg',
    ],
    excerpt: 'Starburst is a visually stunning slot with simple yet engaging gameplay and frequent wins.',
    body: 'Starburst by NetEnt is a fan-favorite slot known for its vibrant colors and simple mechanics. With 10 paylines, expanding wilds, and a 96.09% RTP, it’s perfect for both new and seasoned players.',
    tags: ['Popular', 'New'],
    featured: true,
    faq: [
      { question: 'What is the RTP of Starburst?', answer: 'The RTP is 96.09%.' },
      { question: 'Does Starburst have free spins?', answer: 'Yes, it offers free spins triggered by wilds.' },
    ],
    status: 'enabled',
  },
  {
    id: 6,
    name: 'Baccarat Live',
    slug: 'baccarat-live',
    softwareProvider: 'Evolution Gaming',
    gameType: 'Live Dealer',
    paylines: 0,
    reels: 0,
    minCoinsPerLine: 0,
    maxCoinsPerLine: 0,
    minCoinsSize: 1,
    maxCoinsSize: 1000,
    rtp: 98.94,
    bonusGame: false,
    progressive: false,
    wildSymbol: false,
    scatterSymbol: false,
    autoplayOption: false,
    multiplier: false,
    freeSpins: false,
    seoTitle: 'Baccarat Live Review 2025',
    metaDescription: 'Experience the elegance of Baccarat Live, a premium live dealer game.',
    featuredLogo: '/images/games/featured/game6.jpg',
    screenshotsGallery: [
      '/images/games/screenshots/baccarat-live-1.jpg',
    ],
    excerpt: 'Baccarat Live offers a sophisticated live dealer experience with high RTP.',
    body: 'Baccarat Live by Evolution Gaming delivers an elegant and fast-paced live dealer experience. With a 98.94% RTP, it’s ideal for players who enjoy strategic card games in a live casino setting.',
    tags: ['Exclusive'],
    featured: false,
    faq: [
      { question: 'What is the RTP of Baccarat Live?', answer: 'The RTP is 98.94%.' },
    ],
    status: 'enabled',
  },
  {
    id: 7,
    name: 'Gonzo’s Quest',
    slug: 'gonzos-quest',
    softwareProvider: 'NetEnt',
    gameType: 'Slot',
    paylines: 20,
    reels: 5,
    minCoinsPerLine: 1,
    maxCoinsPerLine: 5,
    minCoinsSize: 0.01,
    maxCoinsSize: 0.5,
    rtp: 95.97,
    bonusGame: true,
    progressive: false,
    wildSymbol: true,
    scatterSymbol: true,
    autoplayOption: true,
    multiplier: true,
    freeSpins: true,
    seoTitle: 'Gonzo’s Quest Slot Review',
    metaDescription: 'Join Gonzo’s Quest for an adventure-filled slot with cascading reels.',
    featuredLogo: '/images/games/featured/game7.jpg',
    screenshotsGallery: [
      '/images/games/screenshots/gonzos-quest-1.jpg',
      '/images/games/screenshots/gonzos-quest-2.jpg',
    ],
    excerpt: 'Gonzo’s Quest is an adventure-themed slot with cascading reels and exciting features.',
    body: 'Gonzo’s Quest by NetEnt takes players on an adventure with its unique cascading reels and free fall feature. With 20 paylines and a 95.97% RTP, it offers thrilling gameplay and big win potential.',
    tags: ['Popular', 'New'],
    featured: true,
    faq: [
      { question: 'What is the RTP of Gonzo’s Quest?', answer: 'The RTP is 95.97%.' },
      { question: 'Does Gonzo’s Quest have a bonus game?', answer: 'Yes, it includes a Free Fall bonus feature.' },
    ],
    status: 'enabled',
  },
  {
    id: 8,
    name: 'Lightning Roulette',
    slug: 'lightning-roulette',
    softwareProvider: 'Evolution Gaming',
    gameType: 'Live Dealer',
    paylines: 0,
    reels: 0,
    minCoinsPerLine: 0,
    maxCoinsPerLine: 0,
    minCoinsSize: 0.2,
    maxCoinsSize: 500,
    rtp: 97.3,
    bonusGame: true,
    progressive: false,
    wildSymbol: false,
    scatterSymbol: false,
    autoplayOption: false,
    multiplier: true,
    freeSpins: false,
    seoTitle: 'Lightning Roulette Review 2025',
    metaDescription: 'Electrifying wins await in Lightning Roulette, a live dealer game with multipliers.',
    featuredLogo: '/images/games/featured/game8.jpg',
    screenshotsGallery: [
      '/images/games/screenshots/lightning-roulette-1.jpg',
    ],
    excerpt: 'Lightning Roulette adds electrifying multipliers to the classic roulette experience.',
    body: 'Lightning Roulette by Evolution Gaming combines traditional roulette with random multipliers up to 500x. With a 97.3% RTP, it offers a thrilling live dealer experience for all players.',
    tags: ['New', 'Exclusive'],
    featured: true,
    faq: [
      { question: 'What is the RTP of Lightning Roulette?', answer: 'The RTP is 97.3%.' },
      { question: 'What are the multipliers in Lightning Roulette?', answer: 'Multipliers range from 50x to 500x on random numbers.' },
    ],
    status: 'enabled',
  },
  {
    id: 9,
    name: 'Book of Dead',
    slug: 'book-of-dead',
    softwareProvider: 'Playtech',
    gameType: 'Slot',
    paylines: 10,
    reels: 5,
    minCoinsPerLine: 1,
    maxCoinsPerLine: 5,
    minCoinsSize: 0.01,
    maxCoinsSize: 2,
    rtp: 96.21,
    bonusGame: true,
    progressive: false,
    wildSymbol: true,
    scatterSymbol: true,
    autoplayOption: true,
    multiplier: true,
    freeSpins: true,
    seoTitle: 'Book of Dead Slot Review 2025',
    metaDescription: 'Explore ancient tombs in Book of Dead, a high-volatility slot with big wins.',
    featuredLogo: '/images/games/featured/game9.jpg',
    screenshotsGallery: [
      '/images/games/screenshots/book-of-dead-1.jpg',
      '/images/games/screenshots/book-of-dead-2.jpg',
    ],
    excerpt: 'Book of Dead is a high-volatility slot with exciting free spins and expanding symbols.',
    body: 'Book of Dead by Playtech is an Egyptian-themed slot with 10 paylines and a 96.21% RTP. Its free spins feature with expanding symbols offers massive win potential, making it a favorite among slot players.',
    tags: ['Popular', 'High Roller'],
    featured: true,
    faq: [
      { question: 'What is the RTP of Book of Dead?', answer: 'The RTP is 96.21%.' },
      { question: 'Does Book of Dead have free spins?', answer: 'Yes, it offers a free spins feature with expanding symbols.' },
    ],
    status: 'enabled',
  },
  {
    id: 10,
    name: 'Dream Catcher',
    slug: 'dream-catcher',
    softwareProvider: 'Evolution Gaming',
    gameType: 'Live Dealer',
    paylines: 0,
    reels: 0,
    minCoinsPerLine: 0,
    maxCoinsPerLine: 0,
    minCoinsSize: 0.1,
    maxCoinsSize: 1000,
    rtp: 96.58,
    bonusGame: false,
    progressive: false,
    wildSymbol: false,
    scatterSymbol: false,
    autoplayOption: false,
    multiplier: true,
    freeSpins: false,
    seoTitle: 'Dream Catcher Game Review',
    metaDescription: 'Spin the wheel in Dream Catcher, a fun live dealer game with big multipliers.',
    featuredLogo: '/images/games/featured/game10.jpg',
    screenshotsGallery: [
      '/images/games/screenshots/dream-catcher-1.jpg',
    ],
    excerpt: 'Dream Catcher is a vibrant live dealer game with a money wheel and multipliers.',
    body: 'Dream Catcher by Evolution Gaming is a lively live dealer game featuring a colorful money wheel. With multipliers up to 7x and a 96.58% RTP, it’s a fun and engaging option for casual players.',
    tags: ['New', 'Popular'],
    featured: false,
    faq: [
      { question: 'What is the RTP of Dream Catcher?', answer: 'The RTP is 96.58%.' },
      { question: 'Does Dream Catcher have multipliers?', answer: 'Yes, it includes multipliers up to 7x.' },
    ],
    status: 'enabled',
  },
];