export const CasinoBonusesData = [
  {
    id: 1,
    name: 'Welcome Bonus',
    slug: 'grand-fortune-welcome',
    featuredImage: '/images/blog/blog-img1.jpg',
    bonusType: 'Welcome Bonus',
    status: 'enabled',
    lastUpdate: '2025-07-01T10:00:00Z',
  },
  {
    id: 2,
    name: 'Free Spins Package',
    slug: 'lucky-star-free-spins',
    featuredImage: '/images/blog/blog-img2.jpg',
    bonusType: 'Free Spins',
    status: 'enabled',
    lastUpdate: '2025-06-28T14:30:00Z',
  },
  {
    id: 3,
    name: 'No Deposit Bonus',
    slug: 'casino-royal-no-deposit',
    featuredImage: '/images/blog/blog-img3.jpg',
    bonusType: 'No Deposit',
    status: 'disabled',
    lastUpdate: '2025-06-15T09:00:00Z',
  },
  {
    id: 4,
    name: 'Reload Bonus',
    slug: 'golden-crown-reload',
    featuredImage: '/images/blog/blog-img4.jpg',
    bonusType: 'Reload Bonus',
    status: 'enabled',
    lastUpdate: '2025-07-03T16:45:00Z',
  },
  {
    id: 5,
    name: 'High Roller Bonus',
    slug: 'vip-casino-high-roller',
    featuredImage: '/images/blog/blog-img5.jpg',
    bonusType: 'High Roller',
    status: 'enabled',
    lastUpdate: '2025-07-05T12:20:00Z',
  },
  {
    id: 6,
    name: 'Cashback Offer',
    slug: 'lucky-clover-cashback',
    featuredImage: '/images/blog/blog-img6.jpg',
    bonusType: 'Cashback',
    status: 'enabled',
    lastUpdate: '2025-06-30T08:15:00Z',
  },
  {
    id: 7,
    name: 'Loyalty Bonus',
    slug: 'royal-vegas-loyalty',
    featuredImage: '/images/blog/blog-img7.jpg',
    bonusType: 'Loyalty Bonus',
    status: 'enabled',
    lastUpdate: '2025-07-02T11:00:00Z',
  },
  {
    id: 8,
    name: 'Second Deposit Bonus',
    slug: 'spin-palace-second-deposit',
    featuredImage: '/images/blog/blog-img8.jpg',
    bonusType: 'Deposit Bonus',
    status: 'enabled',
    lastUpdate: '2025-06-29T17:30:00Z',
  },
  {
    id: 9,
    name: 'Free Bet Bonus',
    slug: 'betway-free-bet',
    featuredImage: '/images/blog/blog-img9.jpg',
    bonusType: 'Free Bet',
    status: 'enabled',
    lastUpdate: '2025-07-04T13:10:00Z',
  },
  {
    id: 10,
    name: 'VIP Welcome Bonus',
    slug: 'casino-elite-vip-welcome',
    featuredImage: '/images/blog/blog-img10.jpg',
    bonusType: 'Welcome Bonus',
    status: 'enabled',
    lastUpdate: '2025-07-06T09:50:00Z',
  },
];