
export const casinoReviewsData = [
  {
    id: 1,
    name: 'Vegas Rush Casino',
    slug: 'example-casino',
    logo: '/images/casinos/logo/casino1.jpg',
    featuredLogo: '/images/casinos/logo/casino1.jpg',
    rating: 4.5,
    tags: ['New', 'Hot', 'Slots'],
    status: 'enabled',
  },
  {
    id: 2,
    name: 'Jackpot City',
    slug: 'jackpot-city',
    logo: '/images/casinos/logo/casino2.jpg',
    featuredLogo: '/images/casinos/logo/casino2.jpg',
    rating: 5,
    tags: ['Popular', 'Live Dealer'],
    status: 'enabled',
  },
  {
    id: 3,
    name: 'Spin Casino',
    slug: 'spin-casino',
    logo: '/images/casinos/logo/casino3.jpg',
    featuredLogo: '/images/casinos/logo/casino3.jpg',
    rating: 4,
    tags: ['Mobile', 'Rewards'],
    status: 'disabled',
  },
  {
    id: 4,
    name: 'LeoVegas',
    slug: 'leovegas',
    logo: '/images/casinos/logo/casino4.jpg',
    featuredLogo: '/images/casinos/logo/casino4.jpg',
    rating: 4.8,
    tags: ['Sports', 'Jackpots'],
    status: 'enabled',
  },
  {
    id: 5,
    name: 'Microgaming',
    slug: 'microgaming',
    logo: '/images/casinos/logo/casino5.jpg',
    featuredLogo: '/images/casinos/logo/casino5.jpg',
    rating: 4.2,
    tags: ['Casino', 'Live Dealer'],
    status: 'enabled',
  },
  {
    id: 6,
    name: 'NetEnt',
    slug: 'netent',
    logo: '/images/casinos/logo/casino6.jpg',
    featuredLogo: '/images/casinos/logo/casino6.jpg',
    rating: 4.7,
    tags: ['Slots', 'Live Dealer'],
    status: 'enabled',
  },
  {
    id: 7,
    name: 'Gonzo\'s Quest',
    slug: 'gonzos-quest',
    logo: '/images/casinos/logo/casino7.jpg',
    featuredLogo: '/images/casinos/logo/casino7.jpg',
    rating: 4.6,
    tags: ['Slots', 'Live',' Dealer', 'Jackpots', 'Sports'],
    status: 'enabled',
  },
  {
    id: 8,
    name: 'Starburst Xtreme',
    slug: 'starburst-x',
    logo: '/images/casinos/logo/casino8.jpg',
    featuredLogo: '/images/casinos/logo/casino8.jpg',
    rating: 4.9,
    tags: ['Slots', 'Live Dealer'],
    status: 'enabled',
  },
  {
    id: 9,
    name: 'Starburst XXtreme',
    slug: 'starburst-xx',
    logo: '/images/casinos/logo/casino9.jpg',
    featuredLogo: '/images/casinos/logo/casino9.jpg',
    rating: 4.9,
    tags: ['Slots', 'Live Dealer'],
    status: 'enabled',
  },
  {
    id: 10,
    name: 'Starburst XXXtreme',
    slug: 'starburst-xxx',
    logo: '/images/casinos/logo/casino10.jpg',
    featuredLogo: '/images/casinos/logo/casino10.jpg',
    rating: 4.9,
    tags: ['Slots', 'Live Dealer'],
    status: 'enabled',
    },
  
];