export const singleCasinoReviewData = [
  {
    id: 1,
    name: 'Vegas Rush Casino',
    slug: 'example-casino',
    logo: '/images/casinos/logo/casino1.jpg',
    featuredLogo: '/images/casinos/logo/casino1.jpg',
    rating: 4.5,
    tags: ['New', 'Hot', 'Slots'],
    status: 'enabled',
    casinoURL: "https://www.vegasrushcasino.com",
    pros: "Wide selection of games, fast withdrawals, excellent customer support.",
    cons: "Limited payment methods, no live chat 24/7.",
    languages: ["English", "Spanish", "German"],
    dateEstablished: 2010,
    licences: ["Malta Gaming Authority", "UK Gambling Commission"],
    casinoType: ["Instant Play", "Mobile Casino"],
    affiliateProgram: "Vegas Affiliates",
    company: "Vegas Gaming Ltd.",
    countries: ["USA", "Canada", "New Zealand"],
    depositMethods: ["Visa", "MasterCard", "Skrill", "Neteller"],
    withdrawalMethods: ["Visa", "Skrill", "Neteller", "Bank Transfer"],
    withdrawalTimes: "1-3 business days",
    withdrawalLimits: "€5,000 per week",
    softwareProviders: ["NetEnt", "Microgaming", "Play'n GO"],
    gameTypes: ["Slots", "Blackjack", "Roulette"],
    rtp: 96.5,
    seoTitle: "Vegas Rush Casino Review - Play Now!",
    metaDescription: "Read our in-depth review of Vegas Rush Casino and get the best bonuses.",
    screenshotsGallery: [
      "/images/blog/blog-img1.jpg",
      "/images/blog/blog-img2.jpg",
    ],
    excerpt: "Vegas Rush Casino offers a thrilling gaming experience with a vast array of games and generous bonuses.",
    body: "<p>Welcome to our comprehensive review of Vegas Rush Casino...</p>",
    faq: [
      { question: "Is Vegas Rush Casino licensed?", answer: "Yes, it holds licenses from MGA and UKGC." },
      { question: "What games can I play?", answer: "Slots, blackjack, roulette, and more." },
    ],
    liveChatAvailable: true,
    phone: "+1234567890",
    email: "support@vegasrushcasino.com",
    depositLimit: true,
    selfExclusion: true,
    withdrawal: false,
    type: 'Casino',
    updatedBy: 'Scraper',
    lastModified: '2025-07-03 02:15 AM',
  },
  {
    id: 2,
    name: 'Jackpot City',
    slug: 'jackpot-city',
    logo: '/images/casinos/logo/casino2.jpg',
    featuredLogo: '/images/casinos/logo/casino2.jpg',
    rating: 5,
    tags: ['Popular', 'Live Dealer'],
    status: 'enabled',
    casinoURL: "https://www.jackpotcity.com",
    pros: "High payout rates, extensive live dealer games, user-friendly interface.",
    cons: "Limited bonus offers, restricted in some countries.",
    languages: ["English", "French", "Spanish"],
    dateEstablished: 1998,
    licences: ["Malta Gaming Authority"],
    casinoType: ["Instant Play", "Mobile Casino"],
    affiliateProgram: "City Affiliates",
    company: "Bayton Ltd.",
    countries: ["Canada", "New Zealand", "Australia"],
    depositMethods: ["Visa", "MasterCard", "PayPal", "Neteller"],
    withdrawalMethods: ["Visa", "PayPal", "Neteller", "Bank Transfer"],
    withdrawalTimes: "1-5 business days",
    withdrawalLimits: "€4,000 per week",
    softwareProviders: ["Microgaming", "Evolution Gaming"],
    gameTypes: ["Slots", "Blackjack", "Live Dealer"],
    rtp: 97.0,
    seoTitle: "Jackpot City Casino Review - Top Bonuses!",
    metaDescription: "Explore Jackpot City Casino with our detailed review and claim top bonuses.",
    screenshotsGallery: [
      "/images/blog/blog-img3.jpg",
      "/images/blog/blog-img4.jpg",
    ],
    excerpt: "Jackpot City offers an exciting gaming platform with high payouts and live dealer options.",
    body: "<p>Discover the exciting world of Jackpot City Casino in our detailed review...</p>",
    faq: [
      { question: "Is Jackpot City safe?", answer: "Yes, it is licensed by the Malta Gaming Authority." },
      { question: "What games are available?", answer: "Slots, blackjack, live dealer games, and more." },
    ],
    liveChatAvailable: true,
    phone: "+9876543210",
    email: "support@jackpotcity.com",
    depositLimit: true,
    selfExclusion: true,
    withdrawal: false,
    type: 'Casino',
    updatedBy: 'Scraper',
    lastModified: '2025-07-03 02:15 AM',
  },
  {
    id: 3,
    name: 'Spin Casino',
    slug: 'spin-casino',
    logo: '/images/casinos/logo/casino3.jpg',
    featuredLogo: '/images/casinos/logo/casino3.jpg',
    rating: 4,
    tags: ['Mobile', 'Rewards'],
    status: 'disabled',
    casinoURL: "https://www.spincasino.com",
    pros: "Great mobile experience, generous loyalty program, wide game variety.",
    cons: "High wagering requirements, slow customer support response.",
    languages: ["English", "German", "French"],
    dateEstablished: 2001,
    licences: ["Malta Gaming Authority"],
    casinoType: ["Instant Play", "Mobile Casino"],
    affiliateProgram: "Spin Affiliates",
    company: "Bayton Ltd.",
    countries: ["Canada", "Australia", "UK"],
    depositMethods: ["Visa", "MasterCard", "Skrill", "Trustly"],
    withdrawalMethods: ["Visa", "Skrill", "Trustly", "Bank Transfer"],
    withdrawalTimes: "2-5 business days",
    withdrawalLimits: "€4,000 per week",
    softwareProviders: ["Microgaming", "NetEnt"],
    gameTypes: ["Slots", "Roulette", "Blackjack"],
    rtp: 96.0,
    seoTitle: "Spin Casino Review - Mobile Gaming Excellence",
    metaDescription: "Check out Spin Casino for a top-tier mobile gaming experience.",
    screenshotsGallery: [
      "/images/blog/blog-img5.jpg",
      "/images/blog/blog-img6.jpg",
    ],
    excerpt: "Spin Casino provides a robust mobile gaming platform with rewarding loyalty programs.",
    body: "<p>Spin Casino is renowned for its mobile gaming excellence...</p>",
    faq: [
      { question: "Does Spin Casino have a mobile app?", answer: "Yes, it offers a mobile-optimized platform." },
      { question: "What games are offered?", answer: "Slots, roulette, blackjack, and more." },
    ],
    liveChatAvailable: false,
    phone: "+1122334455",
    email: "support@spincasino.com",
    depositLimit: true,
    selfExclusion: true,
    withdrawal: false,
    type: 'Casino',
    updatedBy: 'Scraper',
    lastModified: '2025-07-03 02:15 AM',
  },
  {
    id: 4,
    name: 'LeoVegas',
    slug: 'leovegas',
    logo: '/images/casinos/logo/casino4.jpg',
    featuredLogo: '/images/casinos/logo/casino4.jpg',
    rating: 4.8,
    tags: ['Sports', 'Jackpots'],
    status: 'enabled',
    casinoURL: "https://www.leovegas.com",
    pros: "Award-winning mobile app, huge jackpot games, sports betting available.",
    cons: "Limited withdrawal options, high minimum withdrawal.",
    languages: ["English", "Swedish", "German"],
    dateEstablished: 2012,
    licences: ["Malta Gaming Authority", "UK Gambling Commission"],
    casinoType: ["Instant Play", "Mobile Casino", "Sportsbook"],
    affiliateProgram: "Leo Affiliates",
    company: "LeoVegas Gaming Ltd.",
    countries: ["UK", "Canada", "Sweden"],
    depositMethods: ["Visa", "MasterCard", "PayPal", "Trustly"],
    withdrawalMethods: ["Visa", "PayPal", "Trustly"],
    withdrawalTimes: "1-3 business days",
    withdrawalLimits: "€10,000 per month",
    softwareProviders: ["NetEnt", "Play'n GO", "Evolution Gaming"],
    gameTypes: ["Slots", "Jackpots", "Sports Betting"],
    rtp: 96.8,
    seoTitle: "LeoVegas Casino Review - Jackpots & Sports",
    metaDescription: "LeoVegas offers massive jackpots and sports betting in our detailed review.",
    screenshotsGallery: [
      "/images/blog/blog-img7.jpg",
      "/images/blog/blog-img8.jpg",
    ],
    excerpt: "LeoVegas combines casino gaming with sports betting for a versatile experience.",
    body: "<p>LeoVegas is a top choice for jackpot hunters and sports bettors...</p>",
    faq: [
      { question: "Does LeoVegas offer sports betting?", answer: "Yes, it has a comprehensive sportsbook." },
      { question: "What are the jackpot games?", answer: "Progressive slots and more." },
    ],
    liveChatAvailable: true,
    phone: "+4455667788",
    email: "support@leovegas.com",
    depositLimit: true,
    selfExclusion: true,
    withdrawal: false,
    type: 'Casino',
    updatedBy: 'Scraper',
    lastModified: '2025-07-03 02:15 AM',
  },
  {
    id: 5,
    name: 'Microgaming',
    slug: 'microgaming',
    logo: '/images/casinos/logo/casino5.jpg',
    featuredLogo: '/images/casinos/logo/casino5.jpg',
    rating: 4.2,
    tags: ['Casino', 'Live Dealer'],
    status: 'enabled',
    casinoURL: "https://www.microgamingcasino.com",
    pros: "Exclusive Microgaming titles, reliable platform, good bonuses.",
    cons: "Limited game variety, outdated interface.",
    languages: ["English", "French"],
    dateEstablished: 2005,
    licences: ["Malta Gaming Authority"],
    casinoType: ["Instant Play"],
    affiliateProgram: "Micro Affiliates",
    company: "Microgaming Ltd.",
    countries: ["Canada", "UK"],
    depositMethods: ["Visa", "MasterCard", "Skrill"],
    withdrawalMethods: ["Visa", "Skrill", "Bank Transfer"],
    withdrawalTimes: "2-4 business days",
    withdrawalLimits: "€5,000 per week",
    softwareProviders: ["Microgaming"],
    gameTypes: ["Slots", "Blackjack", "Live Dealer"],
    rtp: 95.8,
    seoTitle: "Microgaming Casino Review - Exclusive Titles",
    metaDescription: "Discover exclusive Microgaming games in our casino review.",
    screenshotsGallery: [
      "/images/blog/blog-img9.jpg",
      "/images/blog/blog-img10.jpg",
    ],
    excerpt: "Microgaming Casino focuses on exclusive titles with a reliable platform.",
    body: "<p>Microgaming Casino offers a unique gaming experience...</p>",
    faq: [
      { question: "What makes Microgaming unique?", answer: "Exclusive game titles from Microgaming." },
      { question: "Are live dealer games available?", answer: "Yes, live dealer games are offered." },
    ],
    liveChatAvailable: true,
    phone: "+9988776655",
    email: "support@microgamingcasino.com",
    depositLimit: true,
    selfExclusion: false,
    withdrawal: false,
    type: 'Casino',
    updatedBy: 'Scraper',
    lastModified: '2025-07-03 02:15 AM',
  },
];